(function(){
'use strict';
var DATA=window.FF_DATA, KEY='ff_checklist_state_v5', state={meta:{},items:{},summary:{}};
try{var raw=localStorage.getItem(KEY);if(raw){state=JSON.parse(raw);}}catch(e){}
function byId(id){return document.getElementById(id)}
function get(path){var a=path.split('.'),v=state,i;for(i=0;i<a.length;i++){if(v==null)return undefined;v=v[a[i]];}return v;}
function set(path,val){var a=path.split('.'),v=state,i;for(i=0;i<a.length-1;i++){if(!v[a[i]])v[a[i]]={};v=v[a[i]];}v[a[a.length-1]]=val;save();}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){}progress();}
function bind(el,path){var v=get(path);if(el.type==='radio'){el.checked=v===el.value;el.addEventListener('change',function(){if(el.checked)set(path,el.value);});}else{if(typeof v==='string')el.value=v;el.addEventListener('input',function(){set(path,el.value);});}}
function pill(name,value,text,path){var l=document.createElement('label'),i=document.createElement('input'),s=document.createElement('span');l.className='pill';i.type='radio';i.name=name;i.value=value;s.textContent=text;l.appendChild(i);l.appendChild(s);bind(i,path);return l;}
function addLabel(parent,text){var d=document.createElement('div');d.className='lbl';d.textContent=text;parent.appendChild(d);}
function renderQuestion(container,text,id){var parts=text.split(/(_{3,})/),blankIndex=0,i;container.appendChild(document.createTextNode((parseInt(id.match(/i(\d+)$/)[1],10)+1)+'. '));for(i=0;i<parts.length;i++){if(/^_{3,}$/.test(parts[i])){var inp=document.createElement('input');inp.type='text';inp.className='inline-blank';inp.setAttribute('inputmode','decimal');inp.setAttribute('aria-label','Заполняемое значение');bind(inp,'items.'+id+'.blanks.'+blankIndex);container.appendChild(inp);blankIndex++;}else if(parts[i]){container.appendChild(document.createTextNode(parts[i]));}}}
var meta=byId('meta');DATA.META.forEach(function(x){var l=document.createElement('label'),sp=document.createElement('span'),inp=document.createElement('input');l.className='field';sp.textContent=x[1];inp.type=x[0]==='datetime'?'datetime-local':'text';l.appendChild(sp);l.appendChild(inp);bind(inp,'meta.'+x[0]);meta.appendChild(l);});
var app=byId('app');
DATA.SECTIONS.forEach(function(sec,si){var section=document.createElement('section'),h=document.createElement('h2'),sm=document.createElement('small');section.className='section';h.textContent=(si+1)+'. '+sec[0]+' ';sm.textContent=sec[1].length+' п.';h.appendChild(sm);section.appendChild(h);sec[1].forEach(function(q,ii){var id='s'+si+'i'+ii,item=document.createElement('div'),question=document.createElement('div');item.className='item';question.className='question';renderQuestion(question,q,id);item.appendChild(question);addLabel(item,'Статус');var ps=document.createElement('div');ps.className='pills';[['yes','Да'],['no','Нет'],['part','Частично'],['na','Н/П']].forEach(function(o){ps.appendChild(pill(id+'_status',o[0],o[1],'items.'+id+'.status'));});item.appendChild(ps);addLabel(item,'Доказательство');var pe=document.createElement('div');pe.className='pills';['Фото','Видео','Со слов'].forEach(function(v){var l=document.createElement('label'),c=document.createElement('input'),s=document.createElement('span');l.className='pill';c.type='checkbox';c.value=v;s.textContent=v;var arr=get('items.'+id+'.evidence')||[];c.checked=arr.indexOf(v)>=0;c.addEventListener('change',function(){var a=(get('items.'+id+'.evidence')||[]).slice(),n=a.indexOf(v);if(c.checked&&n<0)a.push(v);if(!c.checked&&n>=0)a.splice(n,1);set('items.'+id+'.evidence',a);});l.appendChild(c);l.appendChild(s);pe.appendChild(l);});item.appendChild(pe);addLabel(item,'Риск');var pr=document.createElement('div');pr.className='pills';[['low','Низкий'],['mid','Средний'],['high','Высокий']].forEach(function(o){pr.appendChild(pill(id+'_risk',o[0],o[1],'items.'+id+'.risk'));});item.appendChild(pr);var ta=document.createElement('textarea');ta.placeholder='Комментарий / факт / цифра…';bind(ta,'items.'+id+'.comment');item.appendChild(ta);
var pa=document.createElement('div');pa.className='photo-actions';
var cameraLabel=document.createElement('label');cameraLabel.className='photo-action';cameraLabel.textContent='📷 Снять фото';var cameraInput=document.createElement('input');cameraInput.type='file';cameraInput.accept='image/*';cameraInput.setAttribute('capture','environment');cameraLabel.appendChild(cameraInput);
var galleryLabel=document.createElement('label');galleryLabel.className='photo-action';galleryLabel.textContent='🖼 Из галереи';var galleryInput=document.createElement('input');galleryInput.type='file';galleryInput.accept='image/*';galleryInput.multiple=true;galleryLabel.appendChild(galleryInput);
pa.appendChild(cameraLabel);pa.appendChild(galleryLabel);item.appendChild(pa);
var prev=document.createElement('div');prev.className='previews';prev.id='p_'+id;item.appendChild(prev);var pg=document.createElement('div');pg.className='print-gallery';pg.id='pg_'+id;item.appendChild(pg);
function handlePhotoInput(fi){var files=[],z;for(z=0;z<fi.files.length;z++)files.push(fi.files[z]);if(!files.length)return;addPhotos(id,files).then(function(){fi.value='';return drawPhotos(id);});}
cameraInput.addEventListener('change',function(){handlePhotoInput(cameraInput);});galleryInput.addEventListener('change',function(){handlePhotoInput(galleryInput);});
section.appendChild(item);setTimeout(function(){drawPhotos(id);},0);});app.appendChild(section);});
var verdict=byId('verdict');[['Подходит','Подходит'],['Условно подходит','Условно'],['Не подходит','Не подходит']].forEach(function(o){verdict.appendChild(pill('verdict',o[0],o[1],'summary.verdict'));});
var sumFields=document.querySelectorAll('[data-save]'),sf;for(sf=0;sf<sumFields.length;sf++)bind(sumFields[sf],sumFields[sf].getAttribute('data-save'));
function progress(){var d=0,t=0;DATA.SECTIONS.forEach(function(s,si){s[1].forEach(function(_,ii){t++;if(get('items.s'+si+'i'+ii+'.status'))d++;});});byId('prog').textContent=d+' / '+t;byId('fill').style.width=(t?d/t*100:0)+'%';}progress();
var dbp=new Promise(function(resolve,reject){if(!window.indexedDB){reject(new Error('no indexedDB'));return;}var r=indexedDB.open('ff_photos_v2',1);r.onupgradeneeded=function(){var db=r.result;if(!db.objectStoreNames.contains('photos')){var st=db.createObjectStore('photos',{keyPath:'id',autoIncrement:true});st.createIndex('item','item',{unique:false});}};r.onsuccess=function(){resolve(r.result);};r.onerror=function(){reject(r.error);};});
function addPhotos(item,files){return dbp.then(function(db){return Promise.all(files.map(function(file){return new Promise(function(resolve,reject){var tx=db.transaction('photos','readwrite');tx.objectStore('photos').add({item:item,blob:file,created:Date.now(),name:file.name||'',type:file.type||''});tx.oncomplete=resolve;tx.onerror=function(){reject(tx.error);};});}));});}
function listPhotos(item){return dbp.then(function(db){return new Promise(function(resolve,reject){var tx=db.transaction('photos','readonly'),r=tx.objectStore('photos').index('item').getAll(item);r.onsuccess=function(){resolve(r.result||[]);};r.onerror=function(){reject(r.error);};});});}
function delPhoto(id){return dbp.then(function(db){return new Promise(function(resolve,reject){var tx=db.transaction('photos','readwrite');tx.objectStore('photos').delete(id);tx.oncomplete=resolve;tx.onerror=function(){reject(tx.error);};});});}
function clearPhotos(){return dbp.then(function(db){return new Promise(function(resolve,reject){var tx=db.transaction('photos','readwrite');tx.objectStore('photos').clear();tx.oncomplete=resolve;tx.onerror=function(){reject(tx.error);};});}).catch(function(){});}
var thumbUrls={};
function releaseThumbUrls(item){var a=thumbUrls[item]||[],i;for(i=0;i<a.length;i++){try{URL.revokeObjectURL(a[i]);}catch(e){}}thumbUrls[item]=[];}
function drawPhotos(item){var box=byId('p_'+item);if(!box)return Promise.resolve();releaseThumbUrls(item);box.innerHTML='';return listPhotos(item).then(function(list){thumbUrls[item]=[];list.forEach(function(rec,index){var w=document.createElement('div'),img=document.createElement('img'),url=URL.createObjectURL(rec.blob),b=document.createElement('button');w.className='ph';thumbUrls[item].push(url);img.src=url;img.alt='Фото '+(index+1);img.addEventListener('click',function(){openViewer(item,index);});b.type='button';b.textContent='×';b.setAttribute('aria-label','Удалить фото');b.addEventListener('click',function(ev){ev.stopPropagation();delPhoto(rec.id).then(function(){drawPhotos(item);});});w.appendChild(img);w.appendChild(b);box.appendChild(w);});}).catch(function(){});}
var viewer=byId('viewer'),viewerImg=byId('viewerImg'),viewerCount=byId('viewerCount'),viewerStage=byId('viewerStage'),viewerClose=byId('viewerClose');
var viewerList=[],viewerIndex=0,viewerUrl=null,touchStartX=0,touchStartY=0;
function releaseViewerUrl(){if(viewerUrl){try{URL.revokeObjectURL(viewerUrl);}catch(e){}viewerUrl=null;}}
function renderViewer(){if(!viewerList.length)return;releaseViewerUrl();var rec=viewerList[viewerIndex];viewerUrl=URL.createObjectURL(rec.blob);viewerImg.src=viewerUrl;viewerCount.textContent=viewerList.length>1?((viewerIndex+1)+' / '+viewerList.length):'';}
function openViewer(item,index){listPhotos(item).then(function(list){if(!list.length)return;viewerList=list;viewerIndex=Math.max(0,Math.min(index,list.length-1));renderViewer();viewer.classList.add('open');viewer.setAttribute('aria-hidden','false');document.body.classList.add('viewer-open');});}
function closeViewer(){viewer.classList.remove('open');viewer.setAttribute('aria-hidden','true');document.body.classList.remove('viewer-open');viewerImg.removeAttribute('src');releaseViewerUrl();viewerList=[];}
function viewerMove(delta){if(viewerList.length<2)return;viewerIndex=(viewerIndex+delta+viewerList.length)%viewerList.length;renderViewer();}
viewerClose.addEventListener('click',closeViewer);viewer.addEventListener('click',function(e){if(e.target===viewer||e.target===viewerStage)closeViewer();});viewerStage.addEventListener('touchstart',function(e){if(!e.touches||!e.touches.length)return;touchStartX=e.touches[0].clientX;touchStartY=e.touches[0].clientY;},{passive:true});viewerStage.addEventListener('touchend',function(e){if(!e.changedTouches||!e.changedTouches.length)return;var dx=e.changedTouches[0].clientX-touchStartX,dy=e.changedTouches[0].clientY-touchStartY;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy)){viewerMove(dx<0?1:-1);}},{passive:true});
function blobToPrintDataURL(blob){return new Promise(function(resolve,reject){var reader=new FileReader();reader.onerror=function(){reject(reader.error);};reader.onload=function(){var img=new Image();img.onerror=function(){reject(new Error('image decode failed'));};img.onload=function(){try{var maxSide=2200,w=img.naturalWidth||img.width,h=img.naturalHeight||img.height,scale=Math.min(1,maxSide/Math.max(w,h)),cw=Math.max(1,Math.round(w*scale)),ch=Math.max(1,Math.round(h*scale)),canvas=document.createElement('canvas');canvas.width=cw;canvas.height=ch;var ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,cw,ch);ctx.drawImage(img,0,0,cw,ch);resolve(canvas.toDataURL('image/jpeg',0.95));}catch(err){reject(err);}};img.src=reader.result;};reader.readAsDataURL(blob);});}
function clearPrintGalleries(){var gs=document.querySelectorAll('.print-gallery'),i;for(i=0;i<gs.length;i++)gs[i].innerHTML='';}
function buildPrintGallery(item){var box=byId('pg_'+item);if(!box)return Promise.resolve();box.innerHTML='';return listPhotos(item).then(function(list){return Promise.all(list.map(function(rec){return blobToPrintDataURL(rec.blob);})).then(function(urls){var i,row,cell,img;for(i=0;i<urls.length;i++){if(i%2===0){row=document.createElement('div');row.className='print-row';box.appendChild(row);}cell=document.createElement('div');cell.className='print-photo';img=document.createElement('img');img.src=urls[i];img.alt='Фото '+(i+1);cell.appendChild(img);row.appendChild(cell);}return new Promise(function(resolve){var imgs=box.querySelectorAll('img'),left=imgs.length,j;if(!left){resolve();return;}function done(){left--;if(left<=0)resolve();}for(j=0;j<imgs.length;j++){if(imgs[j].complete)done();else{imgs[j].onload=done;imgs[j].onerror=done;}}});});});}
function preparePrint(){clearPrintGalleries();var jobs=[];DATA.SECTIONS.forEach(function(sec,si){sec[1].forEach(function(_,ii){jobs.push(buildPrintGallery('s'+si+'i'+ii));});});return Promise.all(jobs);}
function clearAll(){try{localStorage.removeItem(KEY);}catch(e){}state={meta:{},items:{},summary:{}};return clearPhotos().then(function(){location.reload();});}
var printBtn=byId('print'),clearBtn=byId('export');
printBtn.addEventListener('click',function(){printBtn.disabled=true;byId('status').textContent='Подготавливаю фотографии для PDF…';preparePrint().then(function(){setTimeout(function(){printBtn.disabled=false;byId('status').textContent='PDF готов к сохранению.';window.print();},100);}).catch(function(){printBtn.disabled=false;byId('status').textContent='Не удалось подготовить часть фотографий, попробуйте ещё раз.';});});
window.addEventListener('afterprint',function(){setTimeout(function(){clearPrintGalleries();},300);});
clearBtn.addEventListener('click',function(){if(window.confirm('Очистить все ответы, комментарии и фотографии? Это действие нельзя отменить.')){clearAll();}});
if(navigator.storage&&navigator.storage.persist){navigator.storage.persist().catch(function(){});}byId('status').textContent='Офлайн-режим готов. Ответы сохраняются на устройстве, фото — в IndexedDB.';if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').then(function(){byId('status').textContent='Офлайн-режим готов. Приложение закэшировано для работы без интернета.';}).catch(function(){byId('status').textContent='Чек-лист работает, но Service Worker пока не активирован.';});}
})();