(function(){
'use strict';
var DATA=window.FF_DATA, KEY='ff_checklist_state_v5', state={meta:{},items:{},summary:{}};
try{var raw=localStorage.getItem(KEY); if(raw){state=JSON.parse(raw);}}catch(e){}
function byId(id){return document.getElementById(id)}
function get(path){var a=path.split('.'),v=state,i;for(i=0;i<a.length;i++){if(v==null)return undefined;v=v[a[i]];}return v;}
function set(path,val){var a=path.split('.'),v=state,i;for(i=0;i<a.length-1;i++){if(!v[a[i]])v[a[i]]={};v=v[a[i]];}v[a[a.length-1]]=val;save();}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){}progress();}
function bind(el,path){var v=get(path);if(el.type==='radio'){el.checked=v===el.value;el.addEventListener('change',function(){if(el.checked)set(path,el.value);});}else{if(typeof v==='string')el.value=v;el.addEventListener('input',function(){set(path,el.value);});}}
function pill(name,value,text,path){var l=document.createElement('label');l.className='pill';var i=document.createElement('input');i.type='radio';i.name=name;i.value=value;var s=document.createElement('span');s.textContent=text;l.appendChild(i);l.appendChild(s);bind(i,path);return l;}
function addLabel(parent,text){var d=document.createElement('div');d.className='lbl';d.textContent=text;parent.appendChild(d);}
var meta=byId('meta');DATA.META.forEach(function(x){var l=document.createElement('label');l.className='field';var sp=document.createElement('span');sp.textContent=x[1];var inp=document.createElement('input');inp.type=x[0]==='datetime'?'datetime-local':'text';l.appendChild(sp);l.appendChild(inp);bind(inp,'meta.'+x[0]);meta.appendChild(l);});
var app=byId('app');DATA.SECTIONS.forEach(function(sec,si){var section=document.createElement('section');section.className='section';var h=document.createElement('h2');h.textContent=(si+1)+'. '+sec[0]+' ';var sm=document.createElement('small');sm.textContent=sec[1].length+' п.';h.appendChild(sm);section.appendChild(h);sec[1].forEach(function(q,ii){var id='s'+si+'i'+ii,item=document.createElement('div');item.className='item';var question=document.createElement('div');question.className='question';question.textContent=(ii+1)+'. '+q;item.appendChild(question);addLabel(item,'Статус');var ps=document.createElement('div');ps.className='pills';[['yes','Да'],['no','Нет'],['part','Частично'],['na','Н/П']].forEach(function(o){ps.appendChild(pill(id+'_status',o[0],o[1],'items.'+id+'.status'));});item.appendChild(ps);addLabel(item,'Доказательство');var pe=document.createElement('div');pe.className='pills';['Фото','Видео','Со слов'].forEach(function(v){var l=document.createElement('label');l.className='pill';var c=document.createElement('input');c.type='checkbox';c.value=v;var s=document.createElement('span');s.textContent=v;var arr=get('items.'+id+'.evidence')||[];c.checked=arr.indexOf(v)>=0;c.addEventListener('change',function(){var a=(get('items.'+id+'.evidence')||[]).slice(),n=a.indexOf(v);if(c.checked&&n<0)a.push(v);if(!c.checked&&n>=0)a.splice(n,1);set('items.'+id+'.evidence',a);});l.appendChild(c);l.appendChild(s);pe.appendChild(l);});item.appendChild(pe);addLabel(item,'Риск');var pr=document.createElement('div');pr.className='pills';[['low','Низкий'],['mid','Средний'],['high','Высокий']].forEach(function(o){pr.appendChild(pill(id+'_risk',o[0],o[1],'items.'+id+'.risk'));});item.appendChild(pr);var ta=document.createElement('textarea');ta.placeholder='Комментарий / факт / цифра…';bind(ta,'items.'+id+'.comment');item.appendChild(ta);var pl=document.createElement('label');pl.className='photo';pl.appendChild(document.createTextNode('📷 Добавить фото'));var fi=document.createElement('input');fi.type='file';fi.accept='image/*';fi.setAttribute('capture','environment');fi.multiple=true;pl.appendChild(fi);item.appendChild(pl);var prev=document.createElement('div');prev.className='previews';prev.id='p_'+id;item.appendChild(prev);fi.addEventListener('change',function(){var files=[];for(var z=0;z<fi.files.length;z++)files.push(fi.files[z]);addPhotos(id,files).then(function(){fi.value='';drawPhotos(id);});});section.appendChild(item);setTimeout(function(){drawPhotos(id);},0);});app.appendChild(section);});
var verdict=byId('verdict');[['Подходит','Подходит'],['Условно подходит','Условно'],['Не подходит','Не подходит']].forEach(function(o){verdict.appendChild(pill('verdict',o[0],o[1],'summary.verdict'));});
var sumFields=document.querySelectorAll('[data-save]');for(var sf=0;sf<sumFields.length;sf++)bind(sumFields[sf],sumFields[sf].getAttribute('data-save'));
function progress(){var d=0,t=0;DATA.SECTIONS.forEach(function(s,si){s[1].forEach(function(_,ii){t++;if(get('items.s'+si+'i'+ii+'.status'))d++;});});byId('prog').textContent=d+' / '+t;byId('fill').style.width=(t?d/t*100:0)+'%';}progress();
var dbp=new Promise(function(resolve,reject){if(!window.indexedDB){reject(new Error('no indexedDB'));return;}var r=indexedDB.open('ff_photos_v2',1);r.onupgradeneeded=function(){var db=r.result;if(!db.objectStoreNames.contains('photos')){var st=db.createObjectStore('photos',{keyPath:'id',autoIncrement:true});st.createIndex('item','item',{unique:false});}};r.onsuccess=function(){resolve(r.result);};r.onerror=function(){reject(r.error);};});
function addPhotos(item,files){return dbp.then(function(db){return Promise.all(files.map(function(file){return new Promise(function(resolve,reject){var tx=db.transaction('photos','readwrite');tx.objectStore('photos').add({item:item,blob:file,created:Date.now()});tx.oncomplete=resolve;tx.onerror=function(){reject(tx.error);};});}));});}
function listPhotos(item){return dbp.then(function(db){return new Promise(function(resolve,reject){var tx=db.transaction('photos','readonly'),r=tx.objectStore('photos').index('item').getAll(item);r.onsuccess=function(){resolve(r.result||[]);};r.onerror=function(){reject(r.error);};});});}
function delPhoto(id){return dbp.then(function(db){return new Promise(function(resolve,reject){var tx=db.transaction('photos','readwrite');tx.objectStore('photos').delete(id);tx.oncomplete=resolve;tx.onerror=function(){reject(tx.error);};});});}
function drawPhotos(item){var box=byId('p_'+item);if(!box)return;box.innerHTML='';listPhotos(item).then(function(list){list.forEach(function(rec){var w=document.createElement('div');w.className='ph';var img=document.createElement('img'),url=URL.createObjectURL(rec.blob);img.src=url;img.onload=function(){URL.revokeObjectURL(url);};var b=document.createElement('button');b.type='button';b.textContent='×';b.addEventListener('click',function(){delPhoto(rec.id).then(function(){drawPhotos(item);});});w.appendChild(img);w.appendChild(b);box.appendChild(w);});});}
byId('print').addEventListener('click',function(){window.print();});
byId('export').addEventListener('click',function(){var blob=new Blob([JSON.stringify({version:5,exportedAt:new Date().toISOString(),state:state},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ff-checklist-'+new Date().toISOString().slice(0,10)+'.json';document.body.appendChild(a);a.click();setTimeout(function(){URL.revokeObjectURL(a.href);a.parentNode.removeChild(a);},1000);});
if(navigator.storage&&navigator.storage.persist){navigator.storage.persist().catch(function(){});}
byId('status').textContent='Офлайн-режим готов. Ответы сохраняются на устройстве, фото — в IndexedDB.';
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').then(function(){byId('status').textContent='Офлайн-режим готов. Приложение закэшировано для работы без интернета.';}).catch(function(){byId('status').textContent='Чек-лист работает, но Service Worker пока не активирован.';});}
})();